newbranch #1-readme
gits-takaoka/first-sample pull request #2
Opened 2017-07-28 05:25 UTC by gits-takaoka

Issues #1 対応

2017-07-30 01:12 UTC, gits-fujimoto commented
お、マージもできないか。。
repositoryの設定で、collaboratorとして、追加してください。

2017-07-30 01:12 UTC, gits-fujimoto commented
![image](https://user-images.githubusercontent.com/7441137/28749834-927caeb6-750f-11e7-8eae-dd0a368b1eb0.png)

2017-07-30 01:13 UTC, gits-fujimoto commented
このPRは、現時点で、私には以下のようになってます。

![image](https://user-images.githubusercontent.com/7441137/28749839-b38f8240-750f-11e7-951d-4bce5a0f8fab.png)

2017-07-31 13:03 UTC, ghost requested changes
修正ぷりーず

2017-07-31 13:03 UTC, gits-fujimoto commented on README.md
> +  make pullRequest branch:#1-readme to branch:master
pullRequest を
PullRequest に
変更しますか

2017-08-01 03:32 UTC, gits-takaoka commented
修正しましたのでマージをお願いします。

2017-08-01 14:13 UTC, gits-fujimoto commented
修正したcommit が、pushされてませんね

2017-08-07 07:41 UTC, ghost approved these changes
LGTM

2017-08-07 07:41 UTC, gits-fujimoto commented on README.md
> +  make pullRequest branch:#1-readme to branch:master
ok

2017-08-07 07:41 UTC, merged